global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/rules/*.yml

scrape_configs:
- job_name: test-job
  scrape_interval: 15s
  scrape_timeout: 5s
  metrics_path: /
  scheme: http
  static_configs:
  - targets:
    - target-app:8000
    labels:
      app: test
      datacenter: slu
      environment: prd2
      group: api
      host: target-app:8000
      team: olisipo